# Change these first
owner: iamwarning # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Jorgel, Inc.
    url: https://jorgel.io

assignees: # Users to assign downtime issues (optional)
  - iamwarning

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jorgel.io
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Jorgel Status Page
  introTitle: "**System Status**"
  introMessage: You can check our API, explorers and other service status here.
  navbar:
    - title: Status Page
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Jorgel
      href: https://jorgel.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: &copy; 2022 Jorgel, Inc. | All rights reserved | Powered by [Upptime](https://upptime.js.org)
